/* Kwise World — catalog + taxonomy. Plain JS, attaches to window.KW. */
(function () {
  // ---- Category taxonomy ----
  const CATEGORIES = [
    {
      slug: "phones",
      name: "Phones",
      icon: "phone",
      blurb: "iPhone & Samsung — brand new and clean UK-used.",
      brands: [
        { slug: "iphone", name: "iPhone" },
        { slug: "samsung", name: "Samsung" },
      ],
    },
    {
      slug: "laptops",
      name: "Laptops",
      icon: "laptop",
      blurb: "HP & Lenovo machines for work, school and play.",
      brands: [
        { slug: "hp", name: "HP" },
        { slug: "lenovo", name: "Lenovo" },
      ],
    },
    {
      slug: "accessories",
      name: "Accessories",
      icon: "charger",
      blurb: "Chargers, power banks, cables, pouches & screen guards.",
      brands: [
        { slug: "chargers", name: "Chargers" },
        { slug: "power-banks", name: "Power Banks" },
        { slug: "cables", name: "Cables" },
        { slug: "pouches", name: "Pouches & Cases" },
        { slug: "screen-guards", name: "Screen Guards" },
      ],
    },
    {
      slug: "laptop-accessories",
      name: "Laptop Accessories",
      icon: "battery",
      blurb: "Batteries, adapters, cooling pads & sleeves.",
      brands: [
        { slug: "laptop-batteries", name: "Batteries" },
        { slug: "laptop-chargers", name: "Adapters" },
        { slug: "laptop-other", name: "Cooling & Sleeves" },
      ],
    },
  ];

  // Status vocabulary
  // "Brand New" | "UK-Used" | "Nigeria-Used"
  let n = 0;
  const id = (s) => s;

  // helper to make products
  const P = (o) => ({
    rating: 4.6,
    reviews: 0,
    status: "Brand New",
    badges: [],
    oneTime: false,
    stock: 25,
    colors: [],
    ...o,
  });

  const PRODUCTS = [
    // ===== iPhone =====
    P({ id: "iphone-15-pro-max", name: "iPhone 15 Pro Max", cat: "phones", brand: "iphone", thumb: "phone", tint: "blue",
        price: 1850000, status: "Brand New", rating: 4.9, reviews: 128, badge: "Best Seller", featured: true,
        colors: ["Natural Titanium", "Blue Titanium", "Black Titanium"],
        specs: { Storage: "256GB", Display: "6.7\" Super Retina XDR", Chip: "A17 Pro", Camera: "48MP Triple", Battery: "4441mAh" },
        desc: "The flagship. Titanium build, A17 Pro chip and a 5x telephoto camera. Sealed, with full warranty." }),
    P({ id: "iphone-15", name: "iPhone 15", cat: "phones", brand: "iphone", thumb: "phone", tint: "blue",
        price: 1350000, status: "Brand New", rating: 4.8, reviews: 74, featured: true,
        colors: ["Black", "Blue", "Pink", "Green"],
        specs: { Storage: "128GB", Display: "6.1\" Super Retina XDR", Chip: "A16 Bionic", Camera: "48MP Dual" },
        desc: "Dynamic Island, USB-C and a 48MP main camera in a lighter, friendlier package." }),
    P({ id: "iphone-14-pro", name: "iPhone 14 Pro", cat: "phones", brand: "iphone", thumb: "phone", tint: "blue",
        price: 950000, oldPrice: 1100000, status: "UK-Used", rating: 4.7, reviews: 56,
        specs: { Storage: "256GB", Display: "6.1\" ProMotion", Chip: "A16 Bionic", Camera: "48MP Triple" },
        desc: "Clean UK-used Pro. Battery health 89%+, no scratches, fully tested." }),
    P({ id: "iphone-13", name: "iPhone 13", cat: "phones", brand: "iphone", thumb: "phone", tint: "blue",
        price: 620000, status: "UK-Used", rating: 4.6, reviews: 91,
        specs: { Storage: "128GB", Display: "6.1\" Super Retina XDR", Chip: "A15 Bionic", Camera: "12MP Dual" },
        desc: "The everyday favourite. Excellent UK-used condition, great battery." }),
    P({ id: "iphone-12", name: "iPhone 12", cat: "phones", brand: "iphone", thumb: "phone", tint: "blue",
        price: 470000, status: "UK-Used", rating: 4.5, reviews: 63,
        specs: { Storage: "128GB", Display: "6.1\" Super Retina XDR", Chip: "A14 Bionic", Camera: "12MP Dual" },
        desc: "Still mighty. 5G, flat edges, OLED display. Tested and certified." }),
    P({ id: "iphone-11", name: "iPhone 11", cat: "phones", brand: "iphone", thumb: "phone", tint: "blue",
        price: 330000, status: "UK-Used", rating: 4.4, reviews: 110,
        specs: { Storage: "64GB", Display: "6.1\" Liquid Retina", Chip: "A13 Bionic", Camera: "12MP Dual" },
        desc: "The smart-budget pick. Reliable, clean UK-used units." }),

    // ===== Samsung =====
    P({ id: "galaxy-s24-ultra", name: "Galaxy S24 Ultra", cat: "phones", brand: "samsung", thumb: "phone", tint: "indigo",
        price: 1550000, status: "Brand New", rating: 4.9, reviews: 88, badge: "Best Seller", featured: true,
        colors: ["Titanium Gray", "Titanium Black", "Titanium Violet"],
        specs: { Storage: "256GB", Display: "6.8\" QHD+ AMOLED", Chip: "Snapdragon 8 Gen 3", Camera: "200MP Quad", SPen: "Built-in" },
        desc: "Built-in S Pen, 200MP camera and Galaxy AI. The Android flagship to beat." }),
    P({ id: "galaxy-s23", name: "Galaxy S23", cat: "phones", brand: "samsung", thumb: "phone", tint: "indigo",
        price: 980000, status: "Brand New", rating: 4.7, reviews: 42, featured: true,
        colors: ["Phantom Black", "Cream", "Green"],
        specs: { Storage: "256GB", Display: "6.1\" FHD+ AMOLED", Chip: "Snapdragon 8 Gen 2", Camera: "50MP Triple" },
        desc: "Compact flagship power with all-day battery and a brilliant display." }),
    P({ id: "galaxy-z-flip5", name: "Galaxy Z Flip5", cat: "phones", brand: "samsung", thumb: "phone", tint: "indigo",
        price: 1150000, status: "Brand New", rating: 4.6, reviews: 29,
        colors: ["Mint", "Graphite", "Lavender"],
        specs: { Storage: "256GB", Display: "6.7\" Foldable AMOLED", Chip: "Snapdragon 8 Gen 2", Cover: "3.4\" Flex Window" },
        desc: "Pocketable, foldable, fun. A flagship that folds to half the size." }),
    P({ id: "galaxy-a55", name: "Galaxy A55", cat: "phones", brand: "samsung", thumb: "phone", tint: "indigo",
        price: 520000, status: "Brand New", rating: 4.5, reviews: 37,
        specs: { Storage: "128GB", Display: "6.6\" Super AMOLED", Chip: "Exynos 1480", Camera: "50MP Triple" },
        desc: "Premium mid-ranger: metal frame, big AMOLED, dependable battery." }),
    P({ id: "galaxy-s22", name: "Galaxy S22", cat: "phones", brand: "samsung", thumb: "phone", tint: "indigo",
        price: 560000, status: "UK-Used", rating: 4.5, reviews: 51,
        specs: { Storage: "128GB", Display: "6.1\" AMOLED", Chip: "Snapdragon 8 Gen 1", Camera: "50MP Triple" },
        desc: "Clean UK-used flagship at a smart price. Fully tested." }),
    P({ id: "galaxy-a34", name: "Galaxy A34", cat: "phones", brand: "samsung", thumb: "phone", tint: "indigo",
        price: 310000, status: "UK-Used", rating: 4.3, reviews: 44,
        specs: { Storage: "128GB", Display: "6.6\" Super AMOLED", Chip: "Dimensity 1080", Camera: "48MP Triple" },
        desc: "Big screen, big battery, small price. Great UK-used value." }),

    // ===== HP laptops =====
    P({ id: "hp-spectre-x360", name: "HP Spectre x360", cat: "laptops", brand: "hp", thumb: "laptop", tint: "blue",
        price: 1650000, status: "Brand New", rating: 4.8, reviews: 33, badge: "Best Seller", featured: true,
        specs: { CPU: "Intel Core Ultra 7", RAM: "16GB", Storage: "1TB SSD", Display: "13.5\" 3K2K OLED Touch" },
        desc: "Convertible premium ultrabook. OLED touch display, gem-cut design." }),
    P({ id: "hp-pavilion-15", name: "HP Pavilion 15", cat: "laptops", brand: "hp", thumb: "laptop", tint: "blue",
        price: 780000, status: "Brand New", rating: 4.5, reviews: 28,
        specs: { CPU: "Intel Core i5-1335U", RAM: "16GB", Storage: "512GB SSD", Display: "15.6\" FHD" },
        desc: "The dependable all-rounder for work and study. Fast SSD, full-size keyboard." }),
    P({ id: "hp-elitebook-840", name: "HP EliteBook 840 G7", cat: "laptops", brand: "hp", thumb: "laptop", tint: "blue",
        price: 520000, status: "UK-Used", rating: 4.6, reviews: 47,
        specs: { CPU: "Intel Core i7-10610U", RAM: "16GB", Storage: "512GB SSD", Display: "14\" FHD" },
        desc: "Business-grade build, ex-UK corporate. Tough, fast, professional." }),
    P({ id: "hp-probook-450", name: "HP ProBook 450 G8", cat: "laptops", brand: "hp", thumb: "laptop", tint: "blue",
        price: 410000, status: "UK-Used", rating: 4.4, reviews: 31,
        specs: { CPU: "Intel Core i5-1135G7", RAM: "8GB", Storage: "256GB SSD", Display: "15.6\" FHD" },
        desc: "Reliable workhorse for everyday productivity. Clean UK-used." }),

    // ===== Lenovo laptops =====
    P({ id: "lenovo-thinkpad-x1", name: "Lenovo ThinkPad X1 Carbon", cat: "laptops", brand: "lenovo", thumb: "laptop", tint: "indigo",
        price: 1450000, status: "Brand New", rating: 4.8, reviews: 39, featured: true,
        specs: { CPU: "Intel Core i7-1355U", RAM: "16GB", Storage: "1TB SSD", Display: "14\" 2.8K OLED" },
        desc: "The iconic business ultrabook — featherlight carbon-fibre, legendary keyboard." }),
    P({ id: "lenovo-yoga-slim-7", name: "Lenovo Yoga Slim 7", cat: "laptops", brand: "lenovo", thumb: "laptop", tint: "indigo",
        price: 920000, status: "Brand New", rating: 4.6, reviews: 22,
        specs: { CPU: "AMD Ryzen 7 7840U", RAM: "16GB", Storage: "512GB SSD", Display: "14\" 2.8K OLED" },
        desc: "Slim, stylish and quiet. A gorgeous OLED for creators on the move." }),
    P({ id: "lenovo-ideapad-3", name: "Lenovo IdeaPad 3", cat: "laptops", brand: "lenovo", thumb: "laptop", tint: "indigo",
        price: 450000, status: "Brand New", rating: 4.3, reviews: 41,
        specs: { CPU: "AMD Ryzen 5 7520U", RAM: "8GB", Storage: "512GB SSD", Display: "15.6\" FHD" },
        desc: "Affordable, dependable everyday laptop for school and home." }),
    P({ id: "lenovo-thinkpad-t480", name: "Lenovo ThinkPad T480", cat: "laptops", brand: "lenovo", thumb: "laptop", tint: "indigo",
        price: 380000, status: "UK-Used", rating: 4.5, reviews: 58,
        specs: { CPU: "Intel Core i5-8350U", RAM: "16GB", Storage: "256GB SSD", Display: "14\" FHD" },
        desc: "The bulletproof classic. Ex-UK, dual-battery, endlessly reliable." }),

    // ===== Accessories =====
    P({ id: "charger-20w", name: "20W USB-C Fast Charger", cat: "accessories", brand: "chargers", thumb: "charger", tint: "orange",
        price: 18000, rating: 4.6, reviews: 84, specs: { Output: "20W PD", Port: "USB-C", Box: "Charger only" },
        desc: "Fast, compact USB-C power adapter. Charges iPhone & Galaxy in a hurry." }),
    P({ id: "charger-65w-gan", name: "65W GaN Charger", cat: "accessories", brand: "chargers", thumb: "charger", tint: "orange",
        price: 32000, rating: 4.7, reviews: 52, featured: true, specs: { Output: "65W PD", Ports: "2x USB-C + USB-A", Tech: "GaN" },
        desc: "One small brick for phone, tablet and laptop. GaN-cool and travel-ready." }),
    P({ id: "powerbank-20000", name: "20,000mAh Power Bank", cat: "accessories", brand: "power-banks", thumb: "powerbank", tint: "orange",
        price: 42000, rating: 4.6, reviews: 67, featured: true, specs: { Capacity: "20,000mAh", Output: "22.5W", Ports: "USB-C + 2x USB-A" },
        desc: "Multi-day power for trips and long days. Fast-charge in and out." }),
    P({ id: "powerbank-10000", name: "10,000mAh Slim Power Bank", cat: "accessories", brand: "power-banks", thumb: "powerbank", tint: "orange",
        price: 28000, rating: 4.5, reviews: 39, specs: { Capacity: "10,000mAh", Output: "20W", Ports: "USB-C + USB-A" },
        desc: "Pocket-slim top-up that disappears into a bag." }),
    P({ id: "cable-usbc-lightning", name: "USB-C to Lightning Cable", cat: "accessories", brand: "cables", thumb: "cable", tint: "orange",
        price: 9500, rating: 4.5, reviews: 73, specs: { Length: "1m", Rating: "MFi Certified", Speed: "Fast Charge" },
        desc: "Certified fast-charge cable for iPhone. Built to last." }),
    P({ id: "cable-usbc-braided", name: "Braided USB-C Cable 2m", cat: "accessories", brand: "cables", thumb: "cable", tint: "orange",
        price: 7000, rating: 4.4, reviews: 61, specs: { Length: "2m", Jacket: "Nylon Braided", Speed: "60W" },
        desc: "Long, tough, tangle-free. Reaches from the socket to the sofa." }),
    P({ id: "pouch-leather", name: "Leather Phone Pouch", cat: "accessories", brand: "pouches", thumb: "case", tint: "orange",
        price: 12000, rating: 4.6, reviews: 28, specs: { Material: "PU Leather", Fit: "Universal 6.1–6.8\"" },
        desc: "Slim sleeve that keeps your phone scratch-free in style." }),
    P({ id: "case-clear", name: "Shockproof Clear Case", cat: "accessories", brand: "pouches", thumb: "case", tint: "orange",
        price: 8500, rating: 4.5, reviews: 95, specs: { Material: "TPU + PC", Drop: "2m tested" },
        desc: "Crystal-clear protection that shows off your phone." }),
    P({ id: "screen-guard-tempered", name: "Tempered Glass Screen Guard", cat: "accessories", brand: "screen-guards", thumb: "shield", tint: "orange",
        price: 5000, rating: 4.5, reviews: 142, specs: { Hardness: "9H", Pack: "2-pack + kit" },
        desc: "Crisp, crack-resistant 9H glass. Comes with an alignment kit." }),
    P({ id: "screen-guard-privacy", name: "Privacy Screen Guard", cat: "accessories", brand: "screen-guards", thumb: "shield", tint: "orange",
        price: 7500, rating: 4.4, reviews: 38, specs: { Hardness: "9H", Feature: "28° Privacy Filter" },
        desc: "Keep prying eyes out. Anti-spy 9H tempered glass." }),

    // ===== Laptop accessories =====
    P({ id: "hp-charger-65w", name: "HP 65W Laptop Charger", cat: "laptop-accessories", brand: "laptop-chargers", thumb: "charger", tint: "blue",
        price: 22000, rating: 4.5, reviews: 33, specs: { Output: "65W", Tip: "Blue Pin / USB-C", Fit: "HP Pavilion / EliteBook" },
        desc: "Genuine-grade replacement charger for HP laptops." }),
    P({ id: "lenovo-adapter-65w", name: "Lenovo 65W USB-C Adapter", cat: "laptop-accessories", brand: "laptop-chargers", thumb: "charger", tint: "indigo",
        price: 24000, rating: 4.6, reviews: 27, specs: { Output: "65W", Port: "USB-C", Fit: "ThinkPad / Yoga / IdeaPad" },
        desc: "Slim USB-C power adapter for modern Lenovo machines." }),
    P({ id: "thinkpad-battery", name: "ThinkPad Replacement Battery", cat: "laptop-accessories", brand: "laptop-batteries", thumb: "battery", tint: "indigo",
        price: 38000, rating: 4.4, reviews: 19, featured: true, specs: { Capacity: "57Wh", Cells: "6-cell", Fit: "ThinkPad T-series" },
        desc: "Bring an old ThinkPad back to all-day life." }),
    P({ id: "hp-pavilion-battery", name: "HP Pavilion Battery", cat: "laptop-accessories", brand: "laptop-batteries", thumb: "battery", tint: "blue",
        price: 35000, rating: 4.3, reviews: 21, specs: { Capacity: "41Wh", Cells: "3-cell", Fit: "HP Pavilion 15" },
        desc: "Fresh battery for fading HP Pavilions. Easy swap." }),
    P({ id: "cooling-pad", name: "Laptop Cooling Pad", cat: "laptop-accessories", brand: "laptop-other", thumb: "laptop", tint: "blue",
        price: 19000, rating: 4.5, reviews: 44, specs: { Fans: "5x Quiet", Fit: "Up to 17\"", Ports: "USB Pass-through" },
        desc: "Keep things cool on hot afternoons. Adjustable, quiet fans." }),
    P({ id: "laptop-sleeve", name: "15.6\" Laptop Sleeve", cat: "laptop-accessories", brand: "laptop-other", thumb: "case", tint: "indigo",
        price: 11000, rating: 4.6, reviews: 36, specs: { Fit: "15.6\"", Material: "Water-resistant", Pocket: "Front zip" },
        desc: "Padded, water-resistant protection with a handy front pocket." }),

    // ===== One-Time Offers (single-unit specials) =====
    P({ id: "ot-iphone-14-promax", name: "iPhone 14 Pro Max", cat: "phones", brand: "iphone", thumb: "phone", tint: "blue",
        price: 780000, oldPrice: 980000, status: "Nigeria-Used", oneTime: true, stock: 1, rating: 4.5, reviews: 6,
        note: "Tiny hairline scratch on back glass. Screen flawless. Battery 86%.",
        specs: { Storage: "256GB", Display: "6.7\" ProMotion", Chip: "A16 Bionic", Camera: "48MP Triple" },
        desc: "One unit only. A clean Nigeria-used Pro Max at a price that won't repeat." }),
    P({ id: "ot-galaxy-s23-ultra", name: "Galaxy S23 Ultra", cat: "phones", brand: "samsung", thumb: "phone", tint: "indigo",
        price: 820000, oldPrice: 1000000, status: "UK-Used", oneTime: true, stock: 1, rating: 4.4, reviews: 4,
        note: "Faint single pixel dot, invisible in normal use. S Pen included.",
        specs: { Storage: "256GB", Display: "6.8\" QHD+ AMOLED", Chip: "Snapdragon 8 Gen 2", Camera: "200MP Quad" },
        desc: "One unit only. UK-used Ultra with a barely-there blemish and a big discount." }),
    P({ id: "ot-macbook-air-m1", name: "MacBook Air M1", cat: "laptops", brand: "hp", thumb: "laptop", tint: "indigo",
        price: 650000, oldPrice: 820000, status: "Nigeria-Used", oneTime: true, stock: 1, rating: 4.6, reviews: 9,
        note: "Small dent on lid corner. Battery cycle count 210. Runs perfectly.",
        specs: { CPU: "Apple M1", RAM: "8GB", Storage: "256GB SSD", Display: "13.3\" Retina" },
        desc: "One unit only. A silent, fast M1 Air with a cosmetic dent — pure value." }),
    P({ id: "ot-hp-elitebook-dent", name: "HP EliteBook 840 (ex-UK)", cat: "laptops", brand: "hp", thumb: "laptop", tint: "blue",
        price: 360000, oldPrice: 520000, status: "UK-Used", oneTime: true, stock: 1, rating: 4.2, reviews: 3,
        note: "Visible dent on palm rest. Fully functional, keyboard perfect.",
        specs: { CPU: "Intel Core i7-10610U", RAM: "16GB", Storage: "512GB SSD", Display: "14\" FHD" },
        desc: "One unit only. Workhorse EliteBook with a battle scar and a steep markdown." }),
    P({ id: "ot-galaxy-zfold4", name: "Galaxy Z Fold4", cat: "phones", brand: "samsung", thumb: "phone", tint: "indigo",
        price: 720000, oldPrice: 950000, status: "UK-Used", oneTime: true, stock: 1, rating: 4.3, reviews: 5,
        note: "Light crease wear (normal for folds). Hinge tight, no dead pixels.",
        specs: { Storage: "256GB", Display: "7.6\" Foldable AMOLED", Chip: "Snapdragon 8+ Gen 1", Cover: "6.2\" AMOLED" },
        desc: "One unit only. A foldable tablet-phone at an unrepeatable price." }),
    P({ id: "ot-iphone-13-promax", name: "iPhone 13 Pro Max", cat: "phones", brand: "iphone", thumb: "phone", tint: "blue",
        price: 560000, oldPrice: 700000, status: "Nigeria-Used", oneTime: true, stock: 1, rating: 4.5, reviews: 7,
        note: "Aftermarket screen (excellent quality). Body clean. Battery 88%.",
        specs: { Storage: "128GB", Display: "6.7\" ProMotion", Chip: "A15 Bionic", Camera: "12MP Triple" },
        desc: "One unit only. Big-battery Pro Max with a quality replacement screen." }),
  ];

  // Reviews bank (sample, attached per product as needed)
  const REVIEWS = [
    { name: "Chidi O.", rating: 5, date: "2 weeks ago", text: "Exactly as described. Sealed and tested in front of me. Kwise really means what they say.", verified: true },
    { name: "Aisha M.", rating: 5, date: "1 month ago", text: "Fast delivery to Lagos and the phone is perfect. Will buy again.", verified: true },
    { name: "Tunde A.", rating: 4, date: "1 month ago", text: "Good UK-used condition, battery is strong. Minor wear but honestly priced.", verified: true },
    { name: "Grace E.", rating: 5, date: "2 months ago", text: "Customer service answered all my questions on WhatsApp before I paid. Smooth.", verified: true },
    { name: "Emeka N.", rating: 4, date: "3 months ago", text: "Solid device for the money. Came with charger and a free screen guard.", verified: false },
  ];

  function formatNaira(v) {
    return "\u20A6" + Number(v).toLocaleString("en-NG");
  }

  window.KW = { CATEGORIES, PRODUCTS, REVIEWS, formatNaira };
})();
