export interface Laptop {
  id: number;
  name: string;
  brand: "hp" | "dell" | "lenovo" | "acer" | "asus";
  processor: "pentium" | "celeron" | "amd" | "i3" | "i5" | "i7";
  gen: number;          // Intel gen (0 = N/A for Pentium/AMD)
  ram: number;          // GB
  storage: number;      // GB
  storageType: "ssd" | "hdd";
  screen: number;       // inches
  price: number;        // full Naira, e.g. 155000
  touch: boolean;
  kbl: boolean;         // keyboard backlight
  convertible: boolean;
  gpu: boolean;         // dedicated GPU
  highlight: string;    // unique, model-specific one-liner (what makes THIS model distinctive)
}

export const LAPTOPS: Laptop[] = [
  // ── Pentium / Celeron ──────────────────────────────────────────────────────
  { id:  1, name: "Lenovo ThinkPad Yoga 11e", brand: "lenovo", processor: "pentium", gen:  0, ram: 4, storage:  128, storageType: "ssd", screen: 11.6, price: 155000, touch: true,  kbl: false, convertible: true,  gpu: false, highlight: "Rugged MIL-SPEC 2-in-1 with reinforced hinges and rubberized edges — built to survive daily knocks" },
  { id:  2, name: "Lenovo 300e",              brand: "lenovo", processor: "pentium", gen:  0, ram: 4, storage:  128, storageType: "ssd", screen: 11.6, price: 150000, touch: true,  kbl: false, convertible: true,  gpu: false, highlight: "Classroom-tough convertible — MIL-SPEC drop-tested and flips flat to a tablet" },
  { id:  3, name: "Dell Latitude 3190 x360",  brand: "dell",   processor: "pentium", gen:  0, ram: 4, storage:  128, storageType: "ssd", screen: 11.6, price: 120000, touch: false, kbl: false, convertible: true,  gpu: false, highlight: "Rugged 11\" that folds 360° — spill-resistant and light enough for any student bag" },
  { id:  4, name: "Dell Latitude 3190",       brand: "dell",   processor: "pentium", gen:  0, ram: 4, storage:   64, storageType: "ssd", screen: 11.6, price:  95000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Compact, durable education laptop — tough plastic shell, ultra-portable at a low price" },
  { id:  5, name: "Acer Travelmate B118",     brand: "acer",   processor: "celeron", gen:  0, ram: 4, storage:   64, storageType: "ssd", screen: 11.6, price:  95000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Shock-resistant 11\" for students — grippy, drop-tested chassis and all-day battery" },
  { id:  6, name: "Acer Travelmate Spin B3",  brand: "acer",   processor: "celeron", gen:  0, ram: 4, storage:   64, storageType: "ssd", screen: 11.6, price:  95000, touch: false, kbl: false, convertible: true,  gpu: false, highlight: "Rugged 360° convertible with drop protection — made for the rigors of classroom life" },
  { id:  7, name: "HP 250 G4 (Pentium)",      brand: "hp",     processor: "pentium", gen:  0, ram: 4, storage:  500, storageType: "hdd", screen: 15.6, price: 105000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Full 15.6\" screen with a roomy 500GB drive — a simple home laptop with storage to spare" },
  { id:  8, name: "Asus E201N",               brand: "asus",   processor: "celeron", gen:  0, ram: 4, storage:   64, storageType: "ssd", screen: 11.6, price:  95000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Feather-light 11\" ultraportable — long battery life for browsing and note-taking on the go" },
  { id:  9, name: "Asus E410M",               brand: "asus",   processor: "pentium", gen:  0, ram: 4, storage:  128, storageType: "ssd", screen: 14.0, price: 130000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Slim 14\" with all-day battery — a tidy, lightweight pick for everyday tasks" },
  { id: 10, name: "HP 250 G7 (Pentium)",      brand: "hp",     processor: "pentium", gen:  0, ram: 4, storage:  128, storageType: "ssd", screen: 15.6, price: 155000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Big 15.6\" screen on a fast SSD — a no-fuss daily driver that boots in seconds" },
  { id: 11, name: "HP 240 G7 (Pentium)",      brand: "hp",     processor: "pentium", gen:  0, ram: 4, storage:  128, storageType: "ssd", screen: 14.0, price: 160000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Compact 14\" everyday laptop — SSD-quick and easy to carry around all day" },
  { id: 12, name: "Asus E402M",               brand: "asus",   processor: "celeron", gen:  0, ram: 2, storage:  128, storageType: "ssd", screen: 14.0, price: 120000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Ultra-budget 14\" for browsing and typing — light, simple and inexpensive" },

  // ── AMD ────────────────────────────────────────────────────────────────────
  { id: 13, name: "HP Laptop 15 (AMD)",       brand: "hp",     processor: "amd",     gen:  0, ram: 4, storage:  128, storageType: "ssd", screen: 15.6, price: 150000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Wide 15.6\" screen with SSD snappiness — smooth for browsing, streaming and media" },
  { id: 14, name: "HP 245 G8 (AMD)",          brand: "hp",     processor: "amd",     gen:  0, ram: 4, storage:  128, storageType: "ssd", screen: 14.0, price: 160000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Portable 14\" AMD machine — efficient and cool-running for everyday multitasking" },
  { id: 15, name: "HP 255 G7 (AMD)",          brand: "hp",     processor: "amd",     gen:  0, ram: 4, storage:  128, storageType: "ssd", screen: 15.6, price: 155000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Large-screen AMD laptop — comfortable for home use and light office work" },

  // ── Core i3 ────────────────────────────────────────────────────────────────
  { id: 16, name: "Dell Vostro 15-3568",      brand: "dell",   processor: "i3",      gen:  7, ram: 4, storage:  128, storageType: "ssd", screen: 15.6, price: 140000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Small-business 15.6\" — SSD-quick for spreadsheets, email and everyday paperwork" },
  { id: 17, name: "Dell Latitude 3380",       brand: "dell",   processor: "i3",      gen:  6, ram: 4, storage:  128, storageType: "ssd", screen: 13.0, price: 140000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Compact 13\" business build — light and easy to carry between classes or meetings" },
  { id: 18, name: "Acer Aspire E5-475",       brand: "acer",   processor: "i3",      gen:  6, ram: 4, storage:  128, storageType: "ssd", screen: 14.0, price: 120000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Balanced 14\" everyday laptop — SSD boot and a comfortable full-size keyboard" },
  { id: 19, name: "HP ProBook 450 G2",        brand: "hp",     processor: "i3",      gen:  0, ram: 8, storage:  500, storageType: "hdd", screen: 15.6, price: 125000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Business-grade 15.6\" with 8GB RAM — sturdier build than consumer models, roomy storage" },
  { id: 20, name: "HP Pavilion Notebook (i3)",brand: "hp",     processor: "i3",      gen:  5, ram: 8, storage: 1000, storageType: "hdd", screen: 15.6, price: 150000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Massive 1TB storage on a 15.6\" screen — keep all your files, photos and videos in one place" },
  { id: 21, name: "HP 250 G5",               brand: "hp",     processor: "i3",      gen:  5, ram: 8, storage:  500, storageType: "hdd", screen: 15.6, price: 130000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Roomy 15.6\" with 8GB RAM — a dependable machine for everyday office tasks" },
  { id: 22, name: "Lenovo B50-80 / B50-70",  brand: "lenovo", processor: "i3",      gen:  5, ram: 8, storage:  640, storageType: "hdd", screen: 15.6, price: 100000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Big-storage 15.6\" workhorse — 8GB RAM and 640GB drive at a hard-to-beat price" },
  { id: 23, name: "Lenovo B50-50 (i3)",      brand: "lenovo", processor: "i3",      gen:  5, ram: 8, storage:  500, storageType: "hdd", screen: 15.6, price: 120000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Full-size 15.6\" for home and study — 8GB RAM and plenty of storage for the price" },
  { id: 24, name: "HP EliteBook 840 G1 (i3)",brand: "hp",     processor: "i3",      gen:  4, ram: 8, storage:  128, storageType: "ssd", screen: 14.0, price: 180000, touch: true,  kbl: false, convertible: false, gpu: false, highlight: "Premium magnesium-alloy build with a touchscreen — enterprise durability at an entry price" },
  { id: 25, name: "HP EliteBook 820 G1",     brand: "hp",     processor: "i3",      gen:  4, ram: 8, storage:  128, storageType: "ssd", screen: 12.5, price: 160000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Compact 12.5\" business ultrabook with backlit keys — genuinely pocketable and well-built" },
  { id: 26, name: "Dell Latitude 3340 (i3)", brand: "dell",   processor: "i3",      gen:  4, ram: 8, storage:  128, storageType: "ssd", screen: 13.3, price: 140000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Light 13.3\" business laptop — SSD-quick and easy to slip into any bag" },
  { id: 27, name: "Dell Latitude 3550 (i3)", brand: "dell",   processor: "i3",      gen:  4, ram: 8, storage:  500, storageType: "hdd", screen: 15.6, price: 140000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "15.6\" business build with a backlit keyboard — comfortable for long working days" },

  // ── Core i5 ────────────────────────────────────────────────────────────────
  { id: 28, name: "Dell Latitude 3420",          brand: "dell", processor: "i5", gen: 11, ram: 8, storage:  256, storageType: "ssd", screen: 14.0, price: 360000, touch: true,  kbl: true,  convertible: false, gpu: false, highlight: "Modern 11th-gen with touchscreen and backlit keys — the newest, snappiest machine here" },
  { id: 29, name: "Dell Latitude 3410",          brand: "dell", processor: "i5", gen: 10, ram: 8, storage:  256, storageType: "ssd", screen: 14.0, price: 290000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Recent 10th-gen business laptop — fast NVMe SSD and a backlit keyboard for late nights" },
  { id: 30, name: "HP 250 G7 (i5, 10th gen)",   brand: "hp",   processor: "i5", gen: 10, ram: 8, storage:  256, storageType: "ssd", screen: 15.6, price: 250000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Big 15.6\" screen with modern 10th-gen power — strong value in a fast SSD machine" },
  { id: 31, name: "Dell Latitude 5300 2-in-1",  brand: "dell", processor: "i5", gen:  8, ram: 8, storage:  256, storageType: "ssd", screen: 13.0, price: 310000, touch: true,  kbl: true,  convertible: true,  gpu: false, highlight: "Premium metal 2-in-1 — flips to a tablet, touchscreen and backlit keys in a sturdy 13\" body" },
  { id: 32, name: "HP EliteBook 830 G6",        brand: "hp",   processor: "i5", gen:  8, ram: 8, storage:  256, storageType: "ssd", screen: 13.0, price: 300000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Compact 13\" magnesium ultrabook — bright display, Wi-Fi 6 and full enterprise security" },
  { id: 33, name: "Dell Latitude 7490",         brand: "dell", processor: "i5", gen:  8, ram: 8, storage:  256, storageType: "ssd", screen: 14.0, price: 290000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Premium thin-and-light 14\" flagship — magnesium build with long battery and bright screen" },
  { id: 34, name: "Dell Latitude 7290",         brand: "dell", processor: "i5", gen:  8, ram: 8, storage:  256, storageType: "ssd", screen: 12.5, price: 240000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Ultraportable 12.5\" flagship — light, backlit and built for all-day battery on the move" },
  { id: 35, name: "Dell Latitude 5490",         brand: "dell", processor: "i5", gen:  8, ram: 8, storage:  256, storageType: "ssd", screen: 14.0, price: 220000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Mid-range business workhorse — sturdier than budget lines, with plenty of ports" },
  { id: 36, name: "HP EliteBook 840 G5/G6",     brand: "hp",   processor: "i5", gen:  8, ram: 8, storage:  256, storageType: "ssd", screen: 14.0, price: 300000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Magnesium-alloy 14\" ultrabook — MIL-STD durable with one of the best keyboards in business" },
  { id: 37, name: "HP EliteBook 1030 G2",       brand: "hp",   processor: "i5", gen:  7, ram: 8, storage:  256, storageType: "ssd", screen: 13.0, price: 385000, touch: true,  kbl: false, convertible: true,  gpu: false, highlight: "Slim convertible with touchscreen — a premium 13\" that folds flat to a tablet" },
  { id: 38, name: "Dell Latitude 5480",         brand: "dell", processor: "i5", gen:  7, ram: 8, storage:  256, storageType: "ssd", screen: 14.0, price: 220000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Reliable 14\" business build — solid keyboard and easy to service and upgrade" },
  { id: 39, name: "Dell Latitude 7280",         brand: "dell", processor: "i5", gen:  7, ram: 8, storage:  256, storageType: "ssd", screen: 12.5, price: 230000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Premium 12.5\" ultraportable — very light, backlit keys and business-grade build" },
  { id: 40, name: "HP EliteBook 840 G4",        brand: "hp",   processor: "i5", gen:  7, ram: 8, storage:  256, storageType: "ssd", screen: 14.0, price: 260000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Classic magnesium 14\" ultrabook — excellent backlit keyboard and rock-solid reliability" },
  { id: 41, name: "HP EliteBook 840 G4 Touch",  brand: "hp",   processor: "i5", gen:  7, ram: 8, storage:  256, storageType: "ssd", screen: 14.0, price: 280000, touch: true,  kbl: true,  convertible: false, gpu: false, highlight: "Magnesium 14\" business ultrabook with a touchscreen — premium, durable and backlit" },
  { id: 42, name: "HP EliteBook 840 G3 Touch",  brand: "hp",   processor: "i5", gen:  6, ram: 8, storage:  256, storageType: "ssd", screen: 14.0, price: 270000, touch: true,  kbl: true,  convertible: false, gpu: false, highlight: "Durable 14\" business build with touchscreen — enterprise-grade keyboard and metal chassis" },
  { id: 43, name: "HP EliteBook 840 G3",        brand: "hp",   processor: "i5", gen:  6, ram: 8, storage:  256, storageType: "ssd", screen: 14.0, price: 250000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "The magnesium-alloy business classic — superb typing and MIL-STD durability at great value" },
  { id: 44, name: "HP 250 G4 (i5, 6th gen)",   brand: "hp",   processor: "i5", gen:  6, ram: 8, storage:  500, storageType: "hdd", screen: 15.6, price: 140000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Big 15.6\" with real i5 muscle — an affordable everyday office machine with roomy storage" },
  { id: 45, name: "Dell Latitude 3570",         brand: "dell", processor: "i5", gen:  6, ram: 8, storage:  500, storageType: "hdd", screen: 15.6, price: 160000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Large 15.6\" business laptop with backlit keys — comfortable for long typing sessions" },
  { id: 46, name: "Acer Travelmate P258",       brand: "acer", processor: "i5", gen:  6, ram: 8, storage:  500, storageType: "hdd", screen: 15.6, price: 140000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Business-oriented 15.6\" — full-size keyboard and a dependable, no-nonsense build" },
  { id: 47, name: "Dell Latitude E5450 (KBL)",  brand: "dell", processor: "i5", gen:  5, ram: 8, storage:  500, storageType: "hdd", screen: 14.0, price: 160000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "14\" business build with a backlit keyboard — sturdy and reliable for daily office work" },
  { id: 48, name: "Dell Latitude E5450",        brand: "dell", processor: "i5", gen:  5, ram: 8, storage:  500, storageType: "hdd", screen: 14.0, price: 145000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Solid 14\" business laptop — a dependable, budget-friendly pick for office and study" },
  { id: 49, name: "HP EliteBook 840 G2 (i5)",  brand: "hp",   processor: "i5", gen:  5, ram: 8, storage:  500, storageType: "hdd", screen: 14.0, price: 195000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Magnesium 14\" business ultrabook — backlit keys and enterprise durability at a low price" },
  { id: 50, name: "HP 250 G4 (i5, 5th gen)",   brand: "hp",   processor: "i5", gen:  5, ram: 8, storage:  500, storageType: "hdd", screen: 15.6, price: 140000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Full 15.6\" everyday laptop — i5 power and 500GB storage at a friendly price" },
  { id: 51, name: "Dell Latitude 3550 (i5, 1TB)",brand:"dell", processor: "i5", gen:  5, ram: 8, storage: 1000, storageType: "hdd", screen: 15.6, price: 160000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "15.6\" business laptop with a full 1TB drive — massive storage plus a backlit keyboard" },
  { id: 52, name: "Dell Latitude 3550 (i5)",    brand: "dell", processor: "i5", gen:  5, ram: 8, storage:  500, storageType: "hdd", screen: 15.6, price: 150000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Dependable 15.6\" business build — backlit keyboard and comfortable full-size typing" },
  { id: 53, name: "Dell Latitude 3550 (no KBL)",brand: "dell", processor: "i5", gen:  5, ram: 8, storage:  500, storageType: "hdd", screen: 15.6, price: 140000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Straightforward 15.6\" business laptop — i5 power and solid everyday value" },
  { id: 54, name: "Dell Latitude 3450",         brand: "dell", processor: "i5", gen:  5, ram: 8, storage:  500, storageType: "hdd", screen: 14.0, price: 150000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Compact 14\" business build — easy to carry and dependable for daily work" },
  { id: 55, name: "Lenovo B50-50 (i5)",        brand: "lenovo",processor: "i5", gen:  5, ram: 8, storage:  500, storageType: "hdd", screen: 15.6, price: 135000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Big 15.6\" everyday workhorse — i5 power for home and study at a low price" },
  { id: 56, name: "Dell Latitude E7250",        brand: "dell", processor: "i5", gen:  5, ram: 8, storage:  128, storageType: "ssd", screen: 12.5, price: 155000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Ultraportable 12.5\" business ultrabook — SSD-fast, backlit and remarkably light" },
  { id: 57, name: "Acer Aspire E5-573",         brand: "acer", processor: "i5", gen:  5, ram: 8, storage:  500, storageType: "hdd", screen: 15.6, price: 130000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Large 15.6\" everyday all-rounder — a comfortable, affordable machine for home use" },
  { id: 58, name: "HP EliteBook Revolve 810 G2",brand: "hp",   processor: "i5", gen:  4, ram: 8, storage:  256, storageType: "ssd", screen: 12.5, price: 150000, touch: false, kbl: true,  convertible: true,  gpu: false, highlight: "Compact 12.5\" convertible — the display spins to become a tablet, with TPM business security" },
  { id: 59, name: "HP EliteBook 840 G1 (i5)",  brand: "hp",   processor: "i5", gen:  4, ram: 8, storage:  500, storageType: "hdd", screen: 14.0, price: 210000, touch: true,  kbl: true,  convertible: false, gpu: false, highlight: "Magnesium 14\" business classic with a touchscreen — durable build and backlit keys" },
  { id: 60, name: "HP EliteBook Folio 9480m",   brand: "hp",   processor: "i5", gen:  4, ram: 8, storage:  500, storageType: "hdd", screen: 14.0, price: 180000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "One of HP's thinnest business ultrabooks — spill-resistant backlit keyboard and long battery" },
  { id: 61, name: "Dell Latitude E7440",        brand: "dell", processor: "i5", gen:  4, ram: 8, storage:  128, storageType: "ssd", screen: 14.0, price: 155000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Slim 14\" business ultrabook — SSD-fast, backlit and built from premium materials" },
  { id: 62, name: "Dell Latitude E7240",        brand: "dell", processor: "i5", gen:  4, ram: 8, storage:  256, storageType: "ssd", screen: 12.5, price: 165000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Ultraportable 12.5\" — SSD-quick and very light, with a backlit business keyboard" },
  { id: 63, name: "Dell Latitude 3340 (i5)",   brand: "dell", processor: "i5", gen:  4, ram: 8, storage:  128, storageType: "ssd", screen: 13.3, price: 155000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Light 13.3\" business laptop — SSD boot and a compact frame that travels well" },
  { id: 64, name: "HP EliteBook Folio 9470m",   brand: "hp",   processor: "i5", gen:  4, ram: 8, storage:  128, storageType: "ssd", screen: 14.0, price: 175000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "HP's original thinnest EliteBook — SSD-fast, long battery and a spill-resistant keyboard" },
  { id: 65, name: "HP Pavilion 15 (i5)",        brand: "hp",   processor: "i5", gen:  4, ram: 8, storage:  500, storageType: "hdd", screen: 15.6, price: 140000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Large 15.6\" all-rounder — a comfortable big screen for home and general work" },
  { id: 66, name: "HP EliteBook 850 G1",        brand: "hp",   processor: "i5", gen:  4, ram: 8, storage:  500, storageType: "hdd", screen: 15.6, price: 170000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "The 15.6\" EliteBook — big-screen business build with a backlit keyboard and metal chassis" },
  { id: 67, name: "HP ProBook 640 G1",          brand: "hp",   processor: "i5", gen:  4, ram: 8, storage:  128, storageType: "ssd", screen: 14.0, price: 160000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Business-grade 14\" ProBook — sturdier than consumer models and SSD-quick to boot" },
  { id: 68, name: "Acer Travelmate P257",       brand: "acer", processor: "i5", gen:  4, ram: 8, storage:  500, storageType: "hdd", screen: 15.6, price: 130000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Full-size 15.6\" business laptop — dependable everyday build at a value price" },
  { id: 69, name: "Acer Travelmate P253",       brand: "acer", processor: "i5", gen:  0, ram: 8, storage:  500, storageType: "hdd", screen: 15.6, price: 100000, touch: false, kbl: false, convertible: false, gpu: false, highlight: "Roomy 15.6\" for basic office work — the budget-friendly big-screen option" },

  // ── Core i7 ────────────────────────────────────────────────────────────────
  { id: 70, name: "HP EliteBook 840 G5 (i7)",  brand: "hp",   processor: "i7", gen:  8, ram: 8, storage:  256, storageType: "ssd", screen: 14.0, price: 370000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Top-tier i7 in a magnesium 14\" ultrabook — fast, MIL-STD durable and backlit" },
  { id: 71, name: "HP EliteBook 840 G3 (i7)",  brand: "hp",   processor: "i7", gen:  6, ram: 8, storage:  256, storageType: "ssd", screen: 14.0, price: 270000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "i7 power in HP's magnesium business classic — a strong, reliable multitasker" },
  { id: 72, name: "Dell Latitude 7470",         brand: "dell", processor: "i7", gen:  6, ram: 8, storage:  256, storageType: "ssd", screen: 14.0, price: 255000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Premium 14\" ultrabook with i7 — light, bright display and long battery for demanding days" },
  { id: 73, name: "HP EliteBook 840 G2 (i7)",  brand: "hp",   processor: "i7", gen:  5, ram: 8, storage:  500, storageType: "hdd", screen: 14.0, price: 215000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "i7 muscle in a durable 14\" business build — backlit keys and roomy storage" },
  { id: 74, name: "HP EliteBook 820 G2 (i7)",  brand: "hp",   processor: "i7", gen:  5, ram: 8, storage:  128, storageType: "ssd", screen: 12.5, price: 190000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "Compact 12.5\" i7 ultrabook — punchy performance in a genuinely pocketable body" },
  { id: 75, name: "Dell Latitude 7450 (Nvidia)",brand: "dell", processor: "i7", gen:  5, ram: 8, storage:  256, storageType: "ssd", screen: 14.0, price: 230000, touch: false, kbl: false, convertible: false, gpu: true,  highlight: "i7 with a dedicated Nvidia GPU — the pick for light photo/video work and design apps" },
  { id: 76, name: "HP EliteBook 840 G1 (i7)",  brand: "hp",   processor: "i7", gen:  4, ram: 8, storage:  500, storageType: "hdd", screen: 14.0, price: 210000, touch: false, kbl: true,  convertible: false, gpu: false, highlight: "i7 in HP's magnesium business classic — a dependable heavy multitasker with backlit keys" },
];
